apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  namespace: web-app
  labels:
    name: web-app
    apps: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-portfolio
  template:
    metadata:
      labels:
        app: web-app-portfolio
    spec:
      containers:
        - name: web-app-portfolio
          image: franklyn27181/altschool:2.0
          ports:
            - containerPort: 80
